import{S as y,i as n}from"./assets/vendor-BrddEoy-.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();async function p(a){const t="47732907-b8d033787a8c1460109d1a6df",o="https://pixabay.com/api/",s=new URLSearchParams({key:t,q:a,image_type:"photo",orientation:"horizontal",safesearch:!0});try{const e=await fetch(`${o}?${s}`);if(!e.ok)throw new Error("Failed to fetch images");return await e.json()}catch(e){throw console.error(e),e}}function h(a){const t=document.querySelector(".gallery"),o=a.map(({webformatURL:e,largeImageURL:r,tags:i,likes:u,views:m,comments:d,downloads:f})=>`
      <a href="${r}" class="gallery__item">
        <img src="${e}" alt="${i}" class="gallery__image" />
        <div class="info">
          <p><b>Likes:</b> ${u}</p>
          <p><b>Views:</b> ${m}</p>
          <p><b>Comments:</b> ${d}</p>
          <p><b>Downloads:</b> ${f}</p>
        </div>
      </a>
    `).join("");t.innerHTML=o,new y(".gallery a").refresh()}function g(){const a=document.querySelector(".gallery");a.innerHTML=""}const l=document.querySelector(".search-form"),c=document.querySelector("#loader");l.addEventListener("submit",async a=>{a.preventDefault();const t=l.querySelector('input[name="searchQuery"]'),o=t==null?void 0:t.value.trim();if(console.log("Search query value:",o),!o){n.error({title:"Error",message:"Please enter a search term!"});return}g(),c.classList.add("visible");try{const s=await p(o);if(c.classList.remove("visible"),s.hits.length===0){n.warning({title:"No Results",message:"Sorry, there are no images matching your search query."});return}h(s.hits)}catch{c.classList.remove("visible"),n.error({title:"Error",message:"Failed to load images. Please try again later."})}});
//# sourceMappingURL=index.js.map
