import{S as h,i as c}from"./assets/vendor-BrddEoy-.js";(function(){const i=document.createElement("link").relList;if(i&&i.supports&&i.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&o(a)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();async function p(s){const i="47732907-b8d033787a8c1460109d1a6df",t="https://pixabay.com/api/",o=new URLSearchParams({key:i,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0});try{const e=await fetch(`${t}?${o}`);if(!e.ok)throw new Error("Failed to fetch images");return await e.json()}catch(e){throw console.error(e),e}}function y(s){const i=document.querySelector(".gallery"),t=s.map(({webformatURL:e,largeImageURL:r,tags:a,likes:u,views:d,comments:m,downloads:f})=>`
      <a href="${r}" class="gallery__item">
        <img src="${e}" alt="${a}" class="gallery__image" />
        <div class="info">
          <p><b>Likes:</b> ${u}</p>
          <p><b>Views:</b> ${d}</p>
          <p><b>Comments:</b> ${m}</p>
          <p><b>Downloads:</b> ${f}</p>
        </div>
      </a>
    `).join("");i.innerHTML=t,new h(".gallery a").refresh()}function g(){const s=document.querySelector(".gallery");s.innerHTML=""}const l=document.querySelector(".search-form"),n=document.querySelector("#loader");l.addEventListener("submit",function(s){s.preventDefault();const t=l.querySelector('input[name="searchQuery"]').value.trim();if(console.log("Search query value:",t),!t){c.error({title:"Error",message:"Please enter a search term!"});return}g(),n.classList.remove("hidden"),n.classList.add("visible"),p(t).then(function(o){if(n.classList.remove("visible"),n.classList.add("hidden"),o.hits.length===0){c.warning({title:"No Results",message:"Sorry, there are no images matching your search query."});return}y(o.hits)}).catch(function(o){n.classList.remove("visible"),n.classList.add("hidden"),c.error({title:"Error",message:"Failed to load images. Please try again later."})})});
//# sourceMappingURL=index.js.map
